site_name: Interactive Handout

theme:
  feature:
    tabs: true
  name: material

docs_dir: content
site_dir: docs

site_url: https://insper.github.io/interactive-handout/
repo_name: "Interactive Handout"
repo_url: https://github.com/Insper/interactive-handout

nav:
  - Home: index.md
  - Examples:
    - examples/lecture_plus_handout/index.md
    - examples/quiz_and_questions/index.md

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.0.0/js-yaml.min.js
  - js/markdown-enhancer.js

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
