site_name: Interactive Handout

theme:
  feature:
    tabs: true
  name: material

docs_dir: content
site_dir: docs

site_url: https://insper-education.github.io/interactive-handout/
repo_name: "Interactive Handout"
repo_url: https://github.com/insper-education/interactive-handout
edit_uri: edit/main/content/

nav:
  - Home: index.md
  - Reference:
    - reference/slides/index.md
    - reference/quiz/index.md
    - reference/short-questions/index.md

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.0.0/js-yaml.min.js
  - js/markdown-enhancer.js

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details

plugins: 
  - git-revision-date-localized
