extensions:
  - quiz
  - short-questions
  - long-questions
  - progress-check
  - slides
  - counter
  - videos
  - notify-old-page

config:
  short-questions:
      text: "Check"
  counter:
    - question
    - tip
