extensions:
  - translate-admonitions
  - quiz
  - short-questions
  - progress-check
  - slides
  - counter
  - track-links

config:
  short-questions:
      text: "Check"
  counter:
    - question
    - tip
