extensions:
  - translate-admonitions
  - quiz
  - short-questions
  - progress-check
  - slides
  - counter
  - report

config:
  short-questions:
      text: "Check"
  counter:
    - question
    - tip
  report:
      id: "interactive-handout"
      semester: "21a"
      progress: true

      firebase:
        apiKey: "AIzaSyAXVhe_fAYpOE-yQvxelPnq4HMBQGunfxY"
        authDomain: "progress-a14fe.firebaseapp.com"
        databaseURL: "https://progress-a14fe-default-rtdb.firebaseio.com"
        projectId: "progress-a14fe"
        storageBucket: "progress-a14fe.appspot.com"
        messagingSenderId: "941328714948"
        appId: "1:941328714948:web:cd4baa3958d64ec3df4d91"
